---
title: Silas Niewierra
author: Silas Niewierra
email: sniewierra@web.de
description: This portfolio is a showcase of some of the projects I worked on over
  the years. You can find Android applications, as well as various web projects.
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
